openapi: 3.0.0

info:
  title: Fridge pull
  description: Get temperature and presence data from database
  version: 1.0.0

paths:
  /hardware/{macAddress}:
    get:
      summary: Get measurements for MAC address with specified limits
      tags:
        - Hardware
      parameters:
        - name: macAddress
          description: MAC address of module
          in: path
          required: true
          schema:
            type: string
        - name: from
          description: DateTime (ISO 8601-formatted), defaults to 30 days ago
          in: query
          required: true
          schema:
            type: integer
        - name: to
          description: DateTime (ISO 8601-formatted)
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          description: Maximum amount of entries to retrieve
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 1
        - name: offset
          description: Number of entries to skip
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: interval
          description: Minimum amount of seconds between each entry
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/hardware'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'

components:
  schemas:
    hardware:
      type: object
      properties:
        measuredAt:
          type: string
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/sensor'
      example:
        measuredAt: '2021-03-29T21:33:12+02:00'
        sensors:
          - id: 1
            temperature: 7.2
            presence: true
          - id: 2
            temperature: 6.8
            presence: false
          - id: 3
            temperature: 12.6
            presence: true
    sensor:
      type: object
      properties:
        id:
          type: integer
        temperature:
          type: number
        presence:
          type: boolean
      example:
        id: 1
        temperature: 7.2
        presence: true
  responses:
    401:
      description: Access token missing or invalid
    403:
      description: Not authorized to access this resource
    404:
      description: No measurements found
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
